# OAuth callback used by the Google Console and by this application
callback.url=${CALLBACK_URL}

# Google Drive OAuth credentials
provider.googledrive.client-id=${GOOGLE_CLIENT_ID}
provider.googledrive.client-secret=${GOOGLE_CLIENT_SECRET}

provider.googledrive.url-authorize=https://accounts.google.com/o/oauth2/auth
provider.googledrive.url-token=https://oauth2.googleapis.com/token
